project:
  type: book

book:
  title: "Python for Data Analysis Workbook"
  author: "Nghia Nguyen (Mitchell)"
  date: today
  repo-url: https://github.com/nghiaagent/2025-pydata-book
  chapters:
    - index.qmd
    - chapter_2.ipynb
    - chapter_3.ipynb
    - chapter_4.ipynb
    - chapter_5.ipynb
    - chapter_6.ipynb

format:
  html:
    theme: zephyr

editor: source

